config/routes.rb
Folder::Application.routes.draw do
  get "home/index"
resources :uploads do
get 'verify', :on => :collection
post 'download', :on => :collection
end 

   root :to => "home#index"

end

app/models/upload.rb
class Upload < ActiveRecord::Base
 
attr_accessible :folder, :folder_password , :folder_days

has_attached_file :folder
  validates_presence_of :folder_file_name, :folder_password, :folder_days


  validates_length_of :folder_password, :in => 3..12

  validates_numericality_of :folder_days
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController

 def index
    @uploads = Upload.all    
  end

  def show
    @upload = Upload.find(params[:id])
   
  end

  def new
    @upload = Upload.new 
  end

  def edit
    @upload = Upload.find(params[:id])
  end

  def create
   # @upload = Upload.new (params[:upload])
   @upload = Upload.create( params[:upload] )


      if @upload.save
       redirect_to(@upload, :notice => 'document was successfully created.')
      else
    render :action => "new"    
      end
 
  end

  def update
    @upload = Upload.find(params[:id])
      if @upload.update_attributes(params[:upload])
        redirect_to(@upload, :notice => 'upload was successfully updated.')   
      else
        render :action => "edit" 
      
      
    end
  end

  def destroy
    @upload = Upload.find(params[:id])
    @upload.destroy
    redirect_to(uploads_url) 
 
    end

def verify
    @upload = Upload.find(params[:id])

    respond_to do |format|
      if(((Time.now.utc-@upload.created_at)/86400).to_i<@upload.folder_days)
	format.html
      else
	render :text => "Sorry Link expried."
      end
    end
  end

  def download
    @upload = Upload.find(params[:id])

      if(@upload.folder_password == params[:password])
        send_file(@upload.folder.path, :type => @upload.folder_content_type, :disposition => 'inline')
      else
	render :text => "Incorrect password"
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<%= link_to "file uplad", uploads_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Folder</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/uploads/_form.html.erb
<%= form_for(:upload, @upload, :url => uploads_path, :html => {:multipart => true}) do |f| %>
  
<% if @upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this dairy from being saved:</h2>

      <ul>
      <% @upload.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  


<div>

<%= f.label :folder %><br/>
<%= f.file_field :folder %> 

</div>

  <div>
    <%= f.label :password %><br/>
    <%= f.text_field :folder_password %>
  </div><br>

<div>

<%= f.label :days %><br/>
<%= f.text_field :folder_days %> 
</div>
<br>


<br>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/uploads/index.html.erb
<h1>Listing Files</h1>
<%#= link_to "home index", "home/index" %>
<table>
  <tr>
    <th>Filename</th>
   
 
    
   
  </tr>

<% @uploads.each do |upload| %>
  <tr>
    <td width="300px"><%= upload.folder.url %></td>
  
   
    <td width="300px"><%= link_to 'Show', upload %></td>
    
    <td width="300px"><%= link_to 'Destroy', upload, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New File', new_upload_path %>

app/views/uploads/new.html.erb
<h1>New Fileupload</h1>

<%= render 'form' %>

<%= link_to 'Back', uploads_path %>

app/views/uploads/show.html.erb
<%= link_to 'Back', uploads_path %>
<center>
<p id="notice"><%= notice %></p>

<table border=0>
<tr>
<td>File name:</td>
<td><%= @upload.folder_file_name %></td>
</tr>
<tr>
<td>password:</td>
<td><%= @upload.folder_password %></td>
</tr>
</table>
<br>
   <%= link_to "#{@upload.folder.url}", :action => 'verify', :id => @upload.id %><br>


</center>

app/views/uploads/verify.html.erb
<%= form_tag(:action => "download", :method => "get") do %>

  <div class="field">
  <%#= @upload.attach.original_filename %>
  <%= hidden_field_tag :id, @upload.id %>
  <p> Enter password to download file</p>
  </div>

  <div class="field">
    <%= label_tag(:password, "Password:") %>
    <%= text_field_tag(:password) %>
  </div>
 
  <div class="actions">
    <%= submit_tag("Submit") %>
  </div>
<% end %>

<%= link_to 'Back', uploads_path %>